export const CONTRACT_ADDRESS = '0x0000000000000000000000000000000000000000'; // UPDATE AFTER DEPLOYMENT

export const JOURNAL_ABI = [
    {
        inputs: [],
        stateMutability: 'nonpayable',
        type: 'constructor',
    },
    {
        inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
        name: 'OwnableInvalidOwner',
        type: 'error',
    },
    {
        inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
        name: 'OwnableUnauthorizedAccount',
        type: 'error',
    },
    {
        inputs: [],
        name: 'EnforcedPause',
        type: 'error',
    },
    {
        inputs: [],
        name: 'ExpectedPause',
        type: 'error',
    },
    {
        inputs: [],
        name: 'ReentrancyGuardReentrantCall',
        type: 'error',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
            { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
            { indexed: false, internalType: 'string', name: 'title', type: 'string' },
            { indexed: false, internalType: 'bool', name: 'isPrivate', type: 'bool' },
            { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
        ],
        name: 'EntryAdded',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
            { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
        ],
        name: 'EntryDeleted',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
        ],
        name: 'EntryUpdated',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint256', name: 'oldFee', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'newFee', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
        ],
        name: 'EntryFeeUpdated',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
        ],
        name: 'FundsWithdrawn',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
        ],
        name: 'OwnershipTransferred',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
        name: 'Paused',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
            { indexed: false, internalType: 'bool', name: 'isPrivate', type: 'bool' },
            { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
        ],
        name: 'PrivacyToggled',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
        name: 'Unpaused',
        type: 'event',
    },
    {
        inputs: [
            { internalType: 'string', name: '_title', type: 'string' },
            { internalType: 'string', name: '_content', type: 'string' },
            { internalType: 'string', name: '_mood', type: 'string' },
            { internalType: 'string[]', name: '_tags', type: 'string[]' },
            { internalType: 'bool', name: '_isPrivate', type: 'bool' },
        ],
        name: 'addEntry',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '_entryId', type: 'uint256' }],
        name: 'deleteEntry',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256', name: '_entryId', type: 'uint256' },
            { internalType: 'string', name: '_title', type: 'string' },
            { internalType: 'string', name: '_content', type: 'string' },
            { internalType: 'string', name: '_mood', type: 'string' },
            { internalType: 'string[]', name: '_tags', type: 'string[]' },
        ],
        name: 'editEntry',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'entryCounter',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'entryFee',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getBalance',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: '_user', type: 'address' },
            { internalType: 'uint256', name: '_startTime', type: 'uint256' },
            { internalType: 'uint256', name: '_endTime', type: 'uint256' },
        ],
        name: 'getEntriesByDateRange',
        outputs: [
            {
                components: [
                    { internalType: 'uint256', name: 'id', type: 'uint256' },
                    { internalType: 'address', name: 'owner', type: 'address' },
                    { internalType: 'string', name: 'title', type: 'string' },
                    { internalType: 'string', name: 'content', type: 'string' },
                    { internalType: 'string', name: 'mood', type: 'string' },
                    { internalType: 'string[]', name: 'tags', type: 'string[]' },
                    { internalType: 'bool', name: 'isPrivate', type: 'bool' },
                    { internalType: 'uint256', name: 'timestamp', type: 'uint256' },
                    { internalType: 'uint256', name: 'lastEditedAt', type: 'uint256' },
                    { internalType: 'bool', name: 'exists', type: 'bool' },
                    { internalType: 'bool', name: 'deleted', type: 'bool' },
                ],
                internalType: 'struct Journal.Entry[]',
                name: '',
                type: 'tuple[]',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '_entryId', type: 'uint256' }],
        name: 'getEntry',
        outputs: [
            {
                components: [
                    { internalType: 'uint256', name: 'id', type: 'uint256' },
                    { internalType: 'address', name: 'owner', type: 'address' },
                    { internalType: 'string', name: 'title', type: 'string' },
                    { internalType: 'string', name: 'content', type: 'string' },
                    { internalType: 'string', name: 'mood', type: 'string' },
                    { internalType: 'string[]', name: 'tags', type: 'string[]' },
                    { internalType: 'bool', name: 'isPrivate', type: 'bool' },
                    { internalType: 'uint256', name: 'timestamp', type: 'uint256' },
                    { internalType: 'uint256', name: 'lastEditedAt', type: 'uint256' },
                    { internalType: 'bool', name: 'exists', type: 'bool' },
                    { internalType: 'bool', name: 'deleted', type: 'bool' },
                ],
                internalType: 'struct Journal.Entry',
                name: '',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
        name: 'getMoodStats',
        outputs: [
            { internalType: 'string[]', name: 'moods', type: 'string[]' },
            { internalType: 'uint256[]', name: 'counts', type: 'uint256[]' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
        name: 'getUserEntries',
        outputs: [
            {
                components: [
                    { internalType: 'uint256', name: 'id', type: 'uint256' },
                    { internalType: 'address', name: 'owner', type: 'address' },
                    { internalType: 'string', name: 'title', type: 'string' },
                    { internalType: 'string', name: 'content', type: 'string' },
                    { internalType: 'string', name: 'mood', type: 'string' },
                    { internalType: 'string[]', name: 'tags', type: 'string[]' },
                    { internalType: 'bool', name: 'isPrivate', type: 'bool' },
                    { internalType: 'uint256', name: 'timestamp', type: 'uint256' },
                    { internalType: 'uint256', name: 'lastEditedAt', type: 'uint256' },
                    { internalType: 'bool', name: 'exists', type: 'bool' },
                    { internalType: 'bool', name: 'deleted', type: 'bool' },
                ],
                internalType: 'struct Journal.Entry[]',
                name: '',
                type: 'tuple[]',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
        name: 'getUserEntryCount',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'maxEntryLength',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'owner',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'pause',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'paused',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'renounceOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '_entryId', type: 'uint256' }],
        name: 'togglePrivacy',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
        name: 'transferOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'unpause',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '_newFee', type: 'uint256' }],
        name: 'updateFee',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '_newLength', type: 'uint256' }],
        name: 'updateMaxEntryLength',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'withdraw',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
] as const;
